Base.URL=https://www.automationexercise.com
Browser=Chromium
Browser.Version=131.0.6778.33
Playwright.Version=1.49.1
Python.Version=3.11
pytest.Version=8.3.4
Allure.Version=2.38.1
Environment=smoke
Platform=Linux
